name: CI 

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Tree
        uses: actions/checkout@v4

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.13.x

      - name: Install Dependencies
        run: |
          opam install . --deps-only --with-test
          eval $(opam env)

      - name: Build Project
        run: make build
